version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pk178/work:cccd.latest
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - uploads:/app/sources/Database/uploads
      - results:/app/sources/static/results
      - face:/app/sources/static/face
    restart: unless-stopped
    tmpfs:
      - /tmp

volumes:
  uploads:
  results:
  face:
